
services:
  postgres:
    image: postgres:latest
    container_name: shared-postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: quantum123
      POSTGRES_DB: quantum_coders
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend-service
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:quantum123@shared-postgres-db:5432/quantum_coders
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
