#FROM node:18

#WORKDIR /app

#COPY package.json ./
#RUN npm install

#COPY . .

#CMD ["npm", "run", "dev"]
#EXPOSE 3001


# Use an official Node.js runtime as a parent image
FROM node:20

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the port your app runs on
EXPOSE 3001

# Start the application
CMD ["npm", "run", "dev"]
