version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: shared-postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: quantum123
      POSTGRES_DB: quantum_coders
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
